### ISSUE TITLE
Se renseigner sur les capacités de stockage d'Heroku

### ISSUE THREAD

**Issue by leaikkache** [leaikkache/LeaWebsiteFront#11]

**Comment by TatijanaRajcic** [comment]
https://elements.heroku.com/addons/mongolab

**Comment by SelimIkkache** [comment]
On utilise le MongoDb de Heroku : https://elements.heroku.com/addons/mongolab
On à droit à 496 Kb ( ce qui fait déjà pas mal de blogs ...) en free.
